### ISSUE TITLE
no-use-before-define

### ISSUE THREAD

**Issue by misteroneill** [videojs/eslint-config-videojs#10]
```
"no-use-before-define": ["error", {"functions": false}]
```

This form will retain the usefulness of the rule while allowing functions declarations to be used before their declaration appears in code, which is a fairly common pattern in use in our code and elsewhere.
## Old

This would remove the [`"no-use-before-define"`](http://eslint.org/docs/rules/no-use-before-define) rule because it causes code to have to be reorganized in significant ways and makes forms of recursion difficult:

``` js
function a() {
  b();
}

function b() {
  a();
}
```

**Comment by brandonocasey** [comment]
Is that form of recursion something that we want to encourage, would it be easier if `b` just called `b`?

**Comment by misteroneill** [comment]
For example, see [`mergeOptions`](https://github.com/videojs/video.js/blob/master/src/js/utils/merge-options.js).

Added an alternative approach above because I do generally feel like this is a useful rule given some of ES6's new rules around `let`/`const`.

**Comment by brandonocasey** [comment]
couldn't we just do what customizer is doing in a variable that is local to mergeOptions?

``` JavaScript
  args.push(() => {
    if (!isPlain(source)) {
      return source;
    }
    if (!isPlain(destination)) {
      return mergeOptions(source);
    }
  });
```

**Comment by misteroneill** [comment]
Sure, there are other ways to do it, but the idea of our current standardization effort is not refactoring code in a functional way beyond what is necessary to pass the linter.

**Comment by misteroneill** [comment]
PS: I vote for the alternative approach as it's likely compatible with more code, but retains the benefits for the most part.

**Comment by misteroneill** [comment]
Not seeing much consensus here... going to solicit opinions in Slack or **shut it down**.

**Comment by misteroneill** [comment]
@gkatsev said "go for it" so... going for it.
