### ISSUE TITLE
Find a way to check for function argument indent alignment

### ISSUE THREAD

**Issue by brandonocasey** [videojs/eslint-config-videojs#16]
Throughout our projects we have a rule where function arguments that are on a new line have to be aligned like so:

``` js
function(thing, 
         baz, 
         bar) {}
```

It would be nice to have an automated rule warn us when this is not done as it is tedious to code review for. I think we will have to write a custom eslint rule in order for this to work.

**Comment by gkatsev** [comment]
This has been fixed by #33
