### ISSUE TITLE
should the `max-len` rule length allow lines greater than 90 characters?

### ISSUE THREAD

**Issue by brandonocasey** [videojs/eslint-config-videojs#21]
We currently have >400 warnings in `video.js`. Most of them our `max-len` warnings. Does video.js just need to fix this? or is a line length of 90 just too restrictive.

**Comment by gkatsev** [comment]
quoting myself:
> we should at some point go through the long lines and see where they fall. If we're consistently at below 100 and our length is 90, we can bump it up to 100 and then the lines longer than 100 we can change
> but if we're all over the place then we just need to fix it

I.e., if most lines fall at a greater line length, we should change the max to that length and fix the rest of the lines. If there's no median line length, we should go through and fix everything.

**Comment by gkatsev** [comment]
It's been turned off.
