### ISSUE TITLE
We should warn about requiring jsdocs but error if jsdocs that exist are invalid

### ISSUE THREAD

**Issue by brandonocasey** [videojs/eslint-config-videojs#22]
* `valid-jsdoc` should be changed to an error
* Validate that missing jsdocs are only a warning still (the `require-jsdoc` rule)
* Validate that missing jsdocs alongside invalid jsdocs work correctly.

**Comment by gkatsev** [comment]
I think this probably covers it well enough https://github.com/videojs/standard#dont-check-jsdoc
