### ISSUE TITLE
Indent to "first"

### ISSUE THREAD

**Issue by gkatsev** [videojs/eslint-config-videojs#32]
So, the latest version of eslint is stricted with indentation but also provides more control. In Video.js itself, we currently almost always align expressions to the first argument.
For example, we do a lot of things like
```js
foo(bar,
    baz,
    baz,
    boop,
    beep);
```
But we do so with function arguments, arrays, and objects. These are all available as options to the indent rule under:
* `FunctionDeclaration ` and `FunctionExpression` with the `parameters` suboption set to `first`
* `CallExpression` with the `arguments` suboption set to `first`
* `ArrayExpression`, `ObjectExpression`, `ImportDeclaration` all set to `first`

This type of alignment is useful because it shows a clear relationship between the items.

**Comment by misteroneill** [comment]
I thought we did arrays like this:

```js
const foo = [
  'bar',
  'baz'
];
```

**Comment by gkatsev** [comment]
I think we have both? But yeah, you're right. That's more like the style we have mostly.

**Comment by gkatsev** [comment]
Objects may also be like that. So, we should focus on `FunctionDeclaration`, `FunctionExpression`, `CallExpression`, and `ImportDeclaration` for now.

**Comment by misteroneill** [comment]
Personally, I've never liked that style of aligning function arguments because it is awkward looking in certain cases:

```js
some.object.path.and.methodName(foo,
                                bar,
                                baz);
```

My preference is:

```js
some.object.path.and.methodName(
  foo,
  bar,
  baz
);
```

Because it matches the array/object style above and it's a single rule for multiple forms of syntax.

With that said... I'm fine with whatever. It's more important to me to have a standard than what that standard is (within reason, of course).

**Comment by gkatsev** [comment]
I like the alignment but OK with your preference, unfortunately, I don't think eslint can enforce a new line there and I think it looks awkward when you align subsequent lines 1 indent level but keep the first arg on the first line like so:
```js
some.object.path.and.methodName(foo,
  bar,
  baz
);
```

**Comment by misteroneill** [comment]
Yeah, that definitely looks awkward. I'm in favor of whatever can be enforced so I don't have to think about it again! 😆

**Comment by gkatsev** [comment]
Another option is to disable `indent` and enable `indent-legacy` to match old behavior and punt on this issue for now :)

**Comment by gkatsev** [comment]
Asking in eslint chat.

**Comment by gkatsev** [comment]
Looks like there's other options for this: [`function-paren-newline`](https://eslint.org/docs/rules/function-paren-newline). Probably set to `multiline`.
Other options to consider adding: [`array-bracket-newline`](https://eslint.org/docs/rules/array-bracket-newline) and [`array-element-newline`](https://eslint.org/docs/rules/array-element-newline).

Going to try it out and make a PR.

**Comment by gkatsev** [comment]
Also, [`object-property-newline`](https://eslint.org/docs/rules/object-property-newline) and [`object-curly-newline`](https://eslint.org/docs/rules/object-curly-newline) are worth looking at.

**Comment by gkatsev** [comment]
`function-paren-newline` does help with function decls and exprs but not CallExprs

**Comment by gkatsev** [comment]
So, I think we should set `function-paren-newline`, `object-curly-newline`, and `array-backet-newline` to `consistent` and then work with eslint to get a similar one for call expressions, which we can then set.

**Comment by misteroneill** [comment]
That sounds like a plan. 👍

**Comment by gkatsev** [comment]
So, it looks like maybe `function-paren-newline` does do what we want. When I tried to link locally it wasn't working. Investigating now.

**Comment by gkatsev** [comment]
I made this PR https://github.com/videojs/video.js/pull/5413/files?utf8=%E2%9C%93&diff=unified&w=1
with the output of `vjsstandard --fix` with the values of `consistent` for `array-bracket-newline` and `object-curly-newline` and value of `multiline` for `function-paren-newline`.

**Comment by gkatsev** [comment]
And config PR https://github.com/videojs/eslint-config-videojs/pull/33

**Comment by ldayananda** [comment]
Changes in that example LGTM 👍
