### ISSUE TITLE
comma-dangle

### ISSUE THREAD

**Issue by misteroneill** [videojs/eslint-config-videojs#5]
I propose turning _off_ the `comma-dangle` option as Uglify fixes it, so it won't break in IE8.

**Comment by gkatsev** [comment]
Why? uglify fixes it but if you're not running things through uglify or are running the unminified version and expect things to work in ie8 things will break. We shouldn't have trailing commas.

**Comment by misteroneill** [comment]
I can think of 3 reasons off the top of my head:
1. Easier copy/paste (for reordering or whatever purpose).
2. Easier to add new items.
3. Better diffs (adding an item changes one line instead of two).

**Comment by gkatsev** [comment]
sounds like you want comma first objects :P

**Comment by misteroneill** [comment]
NEVER!

**Comment by brandonocasey** [comment]
I like `comma-dangle` but I think there are two many issues that would come up due to IE 8. I think we need a list for all the things to deprecate when IE8 dies...

**Comment by misteroneill** [comment]
That's fair. I didn't think about that fact that people could be using the unminified output, which would preserve the hanging commas.
