### ISSUE TITLE
consider adding markdown plugin

### ISSUE THREAD

**Issue by gkatsev** [videojs/eslint-config-videojs#7]
Allows us to lint code-fenced blocks in markdown: https://github.com/eslint/eslint-plugin-markdown

**Comment by misteroneill** [comment]
That plugin is awesome, but it doesn't work because of a missing dependency in the `latest` version on npm. I'm sure it'll be fixed in short order, but I'd rather not wait on it. Definitely a future addition!

**Comment by brandonocasey** [comment]
could we lock to an older version?

**Comment by misteroneill** [comment]
If you want to see if you can find one that works, by all means! :)
