### ISSUE TITLE
wrap-iife to "any"

### ISSUE THREAD

**Issue by misteroneill** [videojs/eslint-config-videojs#9]
This is a suggestion to change `"wrap-iife": ["error", "outside"]` to `"wrap-iife": ["error", "any"]` meaning the parentheses around an IIFE are required, but they can be inside or outside the invoking parentheses:

``` js
(function() { ... })();
(function() { ... }());
```

**Comment by gkatsev** [comment]
I guess that's fine.
Also, it's possible that when I wrote the rules I misunderstood what the "outside" value meant.

**Comment by brandonocasey** [comment]
would this be major since it is making the rule match more things?

**Comment by misteroneill** [comment]
It's a loosening because it'll fail less often - two forms are acceptable instead of one.

**Comment by brandonocasey** [comment]
ahh ok
